//! Curated catalog of well-known CVEs.
//!
//! A seed set with real CVE ids, CVSS, approximate EPSS and CISA-KEV flags. The
//! full NVD/EPSS/KEV feeds plug in behind the same [`CveRecord`] shape later.
//!
//! Two kinds of records:
//! - **versioned** product entries (`OpenSSH`, `Apache httpd`, â€¦) match when a
//!   service exposes a product string with a version (nmap fingerprints, the
//!   seed, or an imported nmap-XML);
//! - **protocol-level** entries (`smb`, `rdp`, â€¦) use [`VersionRange::Any`] so
//!   they correlate even on a bare connect-scan, where only the service name is
//!   known.
//!
//! Version-checked ranges mirror NVD: a CVE that affects several disjoint
//! product branches with patched gaps uses [`VersionRange::Branches`] (one
//! `[start, fixed)` interval per branch) rather than one continuous
//! [`VersionRange::Range`], so a patched per-branch release between the branches
//! is not flagged. The FF1 harness (`argus-eval`) measures this precision.

use argus_core::Severity;

use crate::{CveRecord, VersionRange};

/// The bundled CVE catalog.
pub const CATALOG: &[CveRecord] = &[
    // ---- Remote access / SSH ----------------------------------------------
    CveRecord {
        cve_id: "CVE-2024-6387",
        product: "OpenSSH",
        // NVD: < 4.4p1, AND 8.5p1..=9.7p1 (regression reintroduced in 8.5p1;
        // 4.4-8.4 not affected). Fix 9.8p1.
        affected: VersionRange::Branches(&[("0", "4.4p1"), ("8.5", "9.8")]),
        cvss: 8.1,
        epss: 0.62,
        kev: true,
        severity: Severity::High,
        summary: "regreSSHion: unauthenticated RCE in OpenSSH server (sshd)",
    },
    CveRecord {
        cve_id: "CVE-2018-15473",
        product: "OpenSSH",
        // NVD: through 7.7 inclusive (versionEndIncluding 7.7), fix 7.8.
        affected: VersionRange::LessThan("7.8"),
        cvss: 5.3,
        epss: 0.78,
        kev: false,
        severity: Severity::Medium,
        summary: "OpenSSH username enumeration via timing/auth response",
    },
    // ---- Web servers ------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2021-41773",
        product: "Apache httpd",
        affected: VersionRange::Exact("2.4.49"),
        cvss: 7.5,
        epss: 0.975,
        kev: true,
        severity: Severity::High,
        summary: "Apache httpd 2.4.49 path traversal and remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2021-42013",
        product: "Apache httpd",
        // NVD: 2.4.49 AND 2.4.50 (incomplete fix for 41773), fix 2.4.51.
        affected: VersionRange::Range("2.4.49", "2.4.50"),
        cvss: 9.8,
        epss: 0.975,
        kev: true,
        severity: Severity::Critical,
        summary: "Apache httpd 2.4.50 path traversal RCE (incomplete fix for 41773)",
    },
    CveRecord {
        cve_id: "CVE-2013-2028",
        product: "nginx",
        affected: VersionRange::Range("1.3.9", "1.4.0"),
        cvss: 7.5,
        epss: 0.51,
        kev: false,
        severity: Severity::High,
        summary: "nginx chunked-transfer stack buffer overflow",
    },
    // ---- FTP / mail -------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2011-2523",
        product: "vsftpd",
        affected: VersionRange::Exact("2.3.4"),
        cvss: 9.8,
        epss: 0.96,
        kev: false,
        severity: Severity::Critical,
        summary: "vsftpd 2.3.4 backdoor command execution",
    },
    CveRecord {
        cve_id: "CVE-2015-3306",
        product: "ProFTPD",
        affected: VersionRange::Exact("1.3.5"),
        cvss: 9.8,
        epss: 0.95,
        kev: false,
        severity: Severity::Critical,
        summary: "ProFTPD 1.3.5 mod_copy unauthenticated remote command execution",
    },
    CveRecord {
        cve_id: "CVE-2019-10149",
        product: "Exim",
        affected: VersionRange::Range("4.87", "4.91"),
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Exim 'Return of the WIZard' remote command execution",
    },
    // ---- SMB / Windows ----------------------------------------------------
    CveRecord {
        cve_id: "CVE-2017-0144",
        product: "smb",
        affected: VersionRange::Any,
        cvss: 8.1,
        epss: 0.94,
        kev: true,
        severity: Severity::High,
        summary: "EternalBlue: SMBv1 remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2020-0796",
        product: "smb",
        affected: VersionRange::Any,
        cvss: 10.0,
        epss: 0.79,
        kev: true,
        severity: Severity::Critical,
        summary: "SMBGhost: SMBv3 compression remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2017-7494",
        product: "Samba",
        // NVD per-branch: 3.5.0..<4.4.14, 4.5.0..<4.5.10, 4.6.0..<4.6.4.
        affected: VersionRange::Branches(&[
            ("3.5.0", "4.4.14"),
            ("4.5.0", "4.5.10"),
            ("4.6.0", "4.6.4"),
        ]),
        cvss: 9.8,
        epss: 0.92,
        kev: true,
        severity: Severity::Critical,
        summary: "SambaCry: writable-share remote code execution",
    },
    // ---- RDP --------------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2019-0708",
        product: "rdp",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.95,
        kev: true,
        severity: Severity::Critical,
        summary: "BlueKeep: Remote Desktop Services remote code execution",
    },
    // ---- TLS / crypto -----------------------------------------------------
    CveRecord {
        cve_id: "CVE-2014-0160",
        product: "OpenSSL",
        affected: VersionRange::Range("1.0.1", "1.0.1f"),
        cvss: 7.5,
        epss: 0.97,
        kev: false,
        severity: Severity::High,
        summary: "Heartbleed: OpenSSL TLS heartbeat memory disclosure",
    },
    // ---- Databases --------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2012-2122",
        product: "MySQL",
        // NVD per-branch: 5.1.x<5.1.63, 5.5.x<5.5.24, 5.6.x<5.6.6.
        affected: VersionRange::Branches(&[
            ("5.1.0", "5.1.63"),
            ("5.5.0", "5.5.24"),
            ("5.6.0", "5.6.6"),
        ]),
        cvss: 5.5,
        epss: 0.60,
        kev: false,
        severity: Severity::Medium,
        summary: "MySQL/MariaDB authentication bypass via memcmp timing",
    },
    CveRecord {
        cve_id: "CVE-2022-0543",
        product: "redis",
        affected: VersionRange::Any,
        cvss: 10.0,
        epss: 0.91,
        kev: true,
        severity: Severity::Critical,
        summary: "Redis Lua sandbox escape leading to remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2015-1427",
        product: "elasticsearch",
        affected: VersionRange::Any,
        cvss: 7.5,
        epss: 0.90,
        kev: true,
        severity: Severity::High,
        summary: "Elasticsearch Groovy scripting sandbox bypass (RCE)",
    },
    // ---- App servers / middleware -----------------------------------------
    CveRecord {
        cve_id: "CVE-2020-1938",
        product: "Tomcat",
        affected: VersionRange::Range("9.0.0", "9.0.30"),
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Ghostcat: Apache Tomcat AJP file read / inclusion to RCE",
    },
    CveRecord {
        cve_id: "CVE-2024-23897",
        product: "Jenkins",
        // Jenkins 2.x weekly line (fixed 2.442); bounded so it cannot match 1.x.
        affected: VersionRange::Range("2.0", "2.441"),
        cvss: 9.8,
        epss: 0.85,
        kev: true,
        severity: Severity::Critical,
        summary: "Jenkins CLI arbitrary file read (path to remote code execution)",
    },
    CveRecord {
        cve_id: "CVE-2021-44228",
        product: "Log4j",
        affected: VersionRange::Any,
        cvss: 10.0,
        epss: 0.975,
        kev: true,
        severity: Severity::Critical,
        summary: "Log4Shell: Apache Log4j2 JNDI remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2022-22965",
        product: "Spring",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.96,
        kev: true,
        severity: Severity::Critical,
        summary: "Spring4Shell: Spring Framework data-binding remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2024-4577",
        product: "PHP",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "PHP-CGI argument injection on Windows (RCE)",
    },
    // ---- Web apps / Java middleware ---------------------------------------
    CveRecord {
        cve_id: "CVE-2019-2725",
        product: "WebLogic",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Oracle WebLogic Server wls9-async deserialization unauthenticated RCE",
    },
    CveRecord {
        cve_id: "CVE-2020-14882",
        product: "WebLogic",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Oracle WebLogic Server admin console unauthenticated RCE",
    },
    CveRecord {
        cve_id: "CVE-2023-46604",
        product: "ActiveMQ",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Apache ActiveMQ OpenWire protocol deserialization remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2017-5638",
        product: "Struts",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Apache Struts 2 Jakarta multipart parser RCE (Equifax breach)",
    },
    CveRecord {
        cve_id: "CVE-2021-22205",
        product: "GitLab",
        affected: VersionRange::Any,
        cvss: 10.0,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "GitLab CE/EE unauthenticated RCE via ExifTool image parsing",
    },
    CveRecord {
        cve_id: "CVE-2018-7600",
        product: "Drupal",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Drupalgeddon2: Drupal core unauthenticated remote code execution",
    },
    // ---- Enterprise edge / collaboration ----------------------------------
    CveRecord {
        cve_id: "CVE-2021-34473",
        product: "Exchange",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.975,
        kev: true,
        severity: Severity::Critical,
        summary: "ProxyShell: Microsoft Exchange pre-auth remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2023-4966",
        product: "Citrix",
        affected: VersionRange::Any,
        cvss: 9.4,
        epss: 0.96,
        kev: true,
        severity: Severity::Critical,
        summary: "CitrixBleed: NetScaler ADC/Gateway session-token disclosure",
    },
    CveRecord {
        cve_id: "CVE-2022-40684",
        product: "FortiOS",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.96,
        kev: true,
        severity: Severity::Critical,
        summary: "Fortinet FortiOS/FortiProxy authentication bypass on admin interface",
    },
    CveRecord {
        cve_id: "CVE-2022-26134",
        product: "Confluence",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.975,
        kev: true,
        severity: Severity::Critical,
        summary: "Atlassian Confluence OGNL injection unauthenticated RCE",
    },
    CveRecord {
        cve_id: "CVE-2021-21972",
        product: "vCenter",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.97,
        kev: true,
        severity: Severity::Critical,
        summary: "VMware vCenter vSphere Client (vROps) unauthenticated RCE",
    },
    // ---- Supply chain -----------------------------------------------------
    CveRecord {
        cve_id: "CVE-2024-3094",
        product: "xz",
        affected: VersionRange::Range("5.6.0", "5.6.1"),
        cvss: 10.0,
        epss: 0.70,
        // Caught before the backdoored 5.6.0/5.6.1 reached stable distros; no
        // evidence of in-the-wild exploitation, so not on the CISA KEV catalog.
        kev: false,
        severity: Severity::Critical,
        summary: "xz/liblzma upstream backdoor (CVE-2024-3094)",
    },
    // ---- IoT cameras ------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2021-36260",
        product: "Hikvision",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.94,
        kev: true,
        severity: Severity::Critical,
        summary: "Hikvision IP camera web server command injection (unauthenticated RCE)",
    },
    CveRecord {
        cve_id: "CVE-2021-33044",
        product: "Dahua",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.88,
        kev: true,
        severity: Severity::Critical,
        summary: "Dahua IP camera/NVR authentication bypass via crafted login",
    },
    CveRecord {
        cve_id: "CVE-2018-10661",
        product: "Axis",
        affected: VersionRange::Any,
        cvss: 9.8,
        epss: 0.70,
        kev: false,
        severity: Severity::Critical,
        summary: "Axis communications camera authorization bypass (chained to RCE)",
    },
    // ---- OT / ICS ---------------------------------------------------------
    CveRecord {
        cve_id: "CVE-2020-15782",
        product: "SIMATIC",
        affected: VersionRange::Any,
        cvss: 8.1,
        epss: 0.20,
        kev: false,
        severity: Severity::High,
        summary: "Siemens SIMATIC S7-1200/1500 memory protection bypass (code read/write)",
    },
    // ---- Expanded set: banner-observable network services (researched + adversarially verified; CVSS/EPSS/KEV from NVD/FIRST/CISA) ----
    CveRecord {
        cve_id: "CVE-2015-1635",
        product: "Microsoft-IIS",
        affected: VersionRange::Range("7.5", "8.5"),
        cvss: 9.8,
        epss: 1.0,
        kev: true,
        severity: Severity::Critical,
        summary: "HTTP.sys Range header RCE/DoS; IIS 7.5-8.5 (Win2008R2 SP1, 2012, 2012R2)",
    },
    CveRecord {
        cve_id: "CVE-2023-25690",
        product: "Apache httpd",
        // 2.4 branch only (fixed 2.4.56); bounded so it cannot match 1.3/2.0/2.2.
        affected: VersionRange::Range("2.4.0", "2.4.55"),
        cvss: 9.8,
        epss: 0.8377,
        kev: false,
        severity: Severity::Critical,
        summary: "mod_proxy RewriteRule HTTP request smuggling / access-control bypass",
    },
    CveRecord {
        cve_id: "CVE-2021-40438",
        product: "Apache httpd",
        // 2.4 branch only (fixed 2.4.49); bounded against ancient-version FP.
        affected: VersionRange::Range("2.4.0", "2.4.48"),
        cvss: 9.0,
        epss: 1.0,
        kev: true,
        severity: Severity::Critical,
        summary: "mod_proxy SSRF: crafted uri-path forwards request to attacker-chosen origin",
    },
    CveRecord {
        cve_id: "CVE-2021-23017",
        product: "nginx",
        affected: VersionRange::Range("0.6.18", "1.20.0"),
        cvss: 7.7,
        epss: 0.5284,
        kev: false,
        severity: Severity::High,
        summary: "DNS resolver off-by-one 1-byte heap overwrite; DoS, potential other impact",
    },
    CveRecord {
        cve_id: "CVE-2022-41741",
        product: "nginx",
        // NVD two ranges: 1.1.3..<1.22.1 AND 1.23.0..<1.23.2 (1.22.1 stable
        // branch got the backported fix, so 1.22.1-1.22.x are not affected).
        affected: VersionRange::Branches(&[("1.1.3", "1.22.1"), ("1.23.0", "1.23.2")]),
        cvss: 7.8,
        epss: 0.0076,
        kev: false,
        severity: Severity::High,
        summary: "ngx_http_mp4_module memory corruption via crafted mp4 (non-default module)",
    },
    CveRecord {
        cve_id: "CVE-2019-20372",
        product: "nginx",
        affected: VersionRange::LessThan("1.17.7"),
        cvss: 5.3,
        epss: 0.1496,
        kev: false,
        severity: Severity::Medium,
        summary: "error_page request smuggling allows reading unauthorized pages",
    },
    CveRecord {
        cve_id: "CVE-2023-38408",
        product: "OpenSSH",
        affected: VersionRange::LessThan("9.3p2"),
        cvss: 9.8,
        epss: 0.7677,
        kev: false,
        severity: Severity::Critical,
        summary: "ssh-agent PKCS#11 untrusted search path enables RCE when agent forwarded to attacker",
    },
    CveRecord {
        cve_id: "CVE-2023-48795",
        product: "OpenSSH",
        affected: VersionRange::LessThan("9.6"),
        cvss: 5.9,
        epss: 0.9331,
        kev: false,
        severity: Severity::Medium,
        summary: "Terrapin: SSH BPP prefix truncation downgrades/weakens channel integrity (MITM)",
    },
    CveRecord {
        cve_id: "CVE-2018-10933",
        product: "libssh",
        // NVD: 0.6.0..<0.7.6 AND 0.8.0..<0.8.4 (0.7.6+ patched line excluded).
        affected: VersionRange::Branches(&[("0.6.0", "0.7.6"), ("0.8.0", "0.8.4")]),
        cvss: 9.1,
        epss: 0.9179,
        kev: false,
        severity: Severity::Critical,
        summary: "Server accepts USERAUTH_SUCCESS from client, bypassing authentication entirely",
    },
    CveRecord {
        cve_id: "CVE-2016-7406",
        product: "dropbear",
        affected: VersionRange::LessThan("2016.74"),
        cvss: 9.8,
        epss: 0.1049,
        kev: false,
        severity: Severity::Critical,
        summary: "Format-string injection via username/hostname allows root RCE on Dropbear server",
    },
    CveRecord {
        cve_id: "CVE-2018-15599",
        product: "dropbear",
        affected: VersionRange::AtMost("2018.76"),
        cvss: 5.3,
        epss: 0.0271,
        kev: false,
        severity: Severity::Medium,
        summary: "recv_msg_userauth_request leaks username validity, enabling user enumeration",
    },
    CveRecord {
        cve_id: "CVE-2010-4344",
        product: "Exim",
        affected: VersionRange::LessThan("4.70"),
        cvss: 9.8,
        epss: 0.7179,
        kev: true,
        severity: Severity::Critical,
        summary: "Heap overflow in string_vformat via crafted SMTP headers gives remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2019-16928",
        product: "Exim",
        affected: VersionRange::Range("4.92", "4.92.2"),
        cvss: 9.8,
        epss: 0.4248,
        kev: true,
        severity: Severity::Critical,
        summary: "Heap overflow in string_vformat via long EHLO command yields remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2019-15846",
        product: "Exim",
        affected: VersionRange::LessThan("4.92.2"),
        cvss: 9.8,
        epss: 0.3574,
        kev: false,
        severity: Severity::Critical,
        summary: "Trailing backslash in SMTP allows remote attackers to execute code as root",
    },
    CveRecord {
        cve_id: "CVE-2023-42115",
        product: "Exim",
        affected: VersionRange::LessThan("4.96.1"),
        cvss: 9.8,
        epss: 0.1004,
        kev: false,
        severity: Severity::Critical,
        summary: "OOB write in SMTP AUTH External authenticator enables unauthenticated remote code execution",
    },
    CveRecord {
        cve_id: "CVE-2020-28021",
        product: "Exim",
        affected: VersionRange::LessThan("4.94.2"),
        cvss: 8.8,
        epss: 0.0406,
        kev: false,
        severity: Severity::High,
        summary: "Authenticated SMTP newline injection into spool file leads to remote code execution as root",
    },
    CveRecord {
        cve_id: "CVE-2024-4040",
        product: "CrushFTP",
        // NVD two branches: 10.0.0..<10.7.1 AND 11.0.0..<11.1.0.
        affected: VersionRange::Branches(&[("10.0.0", "10.7.1"), ("11.0.0", "11.1.0")]),
        cvss: 10.0,
        epss: 0.9954,
        kev: true,
        severity: Severity::Critical,
        summary: "SSTI/VFS sandbox escape allows unauth file read, admin auth bypass and RCE",
    },
    CveRecord {
        cve_id: "CVE-2025-31161",
        product: "CrushFTP",
        // NVD two branches: 10.0.0..<10.8.4 AND 11.0.0..<11.3.1.
        affected: VersionRange::Branches(&[("10.0.0", "10.8.4"), ("11.0.0", "11.3.1")]),
        cvss: 9.8,
        epss: 0.9996,
        kev: true,
        severity: Severity::Critical,
        summary: "AWS4-HMAC (S3) auth race/error-handling allows unauth admin auth bypass",
    },
    CveRecord {
        cve_id: "CVE-2025-54309",
        product: "CrushFTP",
        // NVD two branches: 10.0.0..<10.8.5 AND 11.0.0..<11.3.4_23.
        affected: VersionRange::Branches(&[("10.0.0", "10.8.5"), ("11.0.0", "11.3.4_23")]),
        cvss: 9.8,
        epss: 0.9166,
        kev: true,
        severity: Severity::Critical,
        summary: "AS2 validation flaw grants remote admin access via HTTPS when DMZ proxy unused",
    },
    CveRecord {
        cve_id: "CVE-2019-12815",
        product: "ProFTPD",
        affected: VersionRange::AtMost("1.3.5b"),
        cvss: 9.8,
        epss: 0.5761,
        kev: false,
        severity: Severity::Critical,
        summary: "mod_copy SITE CPFR/CPTO arbitrary file copy enabling unauth RCE",
    },
    CveRecord {
        cve_id: "CVE-2020-9273",
        product: "ProFTPD",
        affected: VersionRange::Exact("1.3.7"),
        cvss: 8.8,
        epss: 0.1205,
        kev: false,
        severity: Severity::High,
        summary: "Use-after-free in alloc_pool via interrupted transfer; needs auth (PR:L), possible RCE",
    },
    CveRecord {
        cve_id: "CVE-2023-51713",
        product: "ProFTPD",
        affected: VersionRange::LessThan("1.3.8a"),
        cvss: 7.5,
        epss: 0.0425,
        kev: false,
        severity: Severity::High,
        summary: "One-byte OOB read in make_ftp_cmd crashes daemon (DoS) via quote/backslash handling",
    },
    CveRecord {
        cve_id: "CVE-2022-24706",
        product: "CouchDB",
        affected: VersionRange::LessThan("3.2.2"),
        cvss: 9.8,
        epss: 0.9234,
        kev: true,
        severity: Severity::Critical,
        summary: "Default Erlang cookie on epmd/dist port lets unauth attacker gain admin and RCE",
    },
    CveRecord {
        cve_id: "CVE-2025-14847",
        product: "MongoDB",
        // NVD per-branch (MongoBleed): 8.2<8.2.3, 8.0<8.0.17, 7.0<7.0.28,
        // 6.0<6.0.27, 5.0<5.0.32, 4.4<4.4.30 (EOL 4.2/4.0/3.6 have no fix).
        affected: VersionRange::Branches(&[
            ("8.2.0", "8.2.3"),
            ("8.0.0", "8.0.17"),
            ("7.0.0", "7.0.28"),
            ("6.0.0", "6.0.27"),
            ("5.0.0", "5.0.32"),
            ("4.4.0", "4.4.30"),
        ]),
        cvss: 7.5,
        epss: 0.8301,
        kev: true,
        severity: Severity::High,
        summary: "MongoBleed: zlib header length mismatch leaks uninitialized heap memory unauth",
    },
    CveRecord {
        cve_id: "CVE-2025-49844",
        product: "redis",
        affected: VersionRange::Any,
        cvss: 9.9,
        epss: 0.8627,
        kev: false,
        severity: Severity::Critical,
        summary: "RediShell: Lua use-after-free via EVAL enables RCE; requires authenticated user (PR:L)",
    },
    CveRecord {
        cve_id: "CVE-2021-27928",
        product: "MariaDB",
        // NVD per-branch: 10.2<10.2.37, 10.3<10.3.28, 10.4<10.4.18, 10.5<10.5.9.
        affected: VersionRange::Branches(&[
            ("10.2.0", "10.2.37"),
            ("10.3.0", "10.3.28"),
            ("10.4.0", "10.4.18"),
            ("10.5.0", "10.5.9"),
        ]),
        cvss: 7.2,
        epss: 0.3844,
        kev: false,
        severity: Severity::High,
        summary: "wsrep_provider eval injection lets SUPER-priv user run OS commands on MariaDB",
    },
    CveRecord {
        cve_id: "CVE-2016-8706",
        product: "Memcached",
        // Last affected 1.4.32; fix landed in 1.4.33 (Talos TALOS-2016-0221).
        affected: VersionRange::LessThan("1.4.33"),
        cvss: 8.1,
        epss: 0.457,
        kev: false,
        severity: Severity::High,
        summary: "Integer overflow in SASL auth parsing causes heap overflow/RCE in memcached (SASL builds)",
    },
    CveRecord {
        cve_id: "CVE-2025-24813",
        product: "Tomcat",
        affected: VersionRange::Range("9.0.0", "9.0.98"),
        cvss: 9.8,
        epss: 0.9995,
        kev: true,
        severity: Severity::Critical,
        summary: "Partial PUT + file-based session persistence enables unauthenticated RCE",
    },
    CveRecord {
        cve_id: "CVE-2017-12615",
        product: "Tomcat",
        affected: VersionRange::Range("7.0.0", "7.0.79"),
        cvss: 8.1,
        epss: 0.9961,
        kev: true,
        severity: Severity::High,
        summary: "PUT with readonly=false uploads JSP -> RCE on Windows (Tomcat 7)",
    },
    CveRecord {
        cve_id: "CVE-2020-9484",
        product: "Tomcat",
        affected: VersionRange::Range("9.0.0", "9.0.34"),
        cvss: 7.0,
        epss: 0.5664,
        kev: false,
        severity: Severity::High,
        summary: "PersistentManager FileStore session deserialization leads to RCE (local vector)",
    },
    CveRecord {
        cve_id: "CVE-2016-3088",
        product: "ActiveMQ",
        affected: VersionRange::LessThan("5.14.0"),
        cvss: 9.8,
        epss: 0.9852,
        kev: true,
        severity: Severity::Critical,
        summary: "Fileserver web app PUT+MOVE arbitrary file upload -> RCE (5.x before 5.14.0)",
    },
    CveRecord {
        cve_id: "CVE-2017-1000028",
        product: "GlassFish",
        affected: VersionRange::Exact("4.1"),
        cvss: 7.5,
        epss: 0.9948,
        kev: false,
        severity: Severity::High,
        summary: "Unauthenticated path traversal via crafted GET on 4848 admin console",
    },
    CveRecord {
        cve_id: "CVE-2021-43798",
        product: "Grafana",
        affected: VersionRange::Range("8.0.0", "8.3.0"),
        cvss: 7.5,
        epss: 0.8885,
        kev: true,
        severity: Severity::High,
        summary: "Unauthenticated path traversal via /public/plugins/ reads arbitrary local files",
    },
    CveRecord {
        cve_id: "CVE-2023-23752",
        product: "Joomla",
        affected: VersionRange::Range("4.0.0", "4.2.7"),
        cvss: 5.3,
        epss: 0.9983,
        kev: true,
        severity: Severity::Medium,
        summary: "Improper access check exposes webservice API config incl DB credentials",
    },
    CveRecord {
        cve_id: "CVE-2022-21661",
        product: "WordPress",
        // Per-branch backports; verified subset (older branches under-covered
        // rather than guessed): 4.7<4.7.22, 5.7<5.7.5, 5.8<5.8.3.
        affected: VersionRange::Branches(&[
            ("4.7.0", "4.7.22"),
            ("5.7.0", "5.7.5"),
            ("5.8.0", "5.8.3"),
        ]),
        cvss: 7.5,
        epss: 0.978,
        kev: false,
        severity: Severity::High,
        summary: "WP_Query SQL injection via crafted tax_query/meta_query in WordPress core",
    },
    CveRecord {
        cve_id: "CVE-2018-12613",
        product: "phpMyAdmin",
        affected: VersionRange::Range("4.8.0", "4.8.1"),
        cvss: 8.8,
        epss: 0.9839,
        kev: false,
        severity: Severity::High,
        summary: "LFI via index.php target param leads to PHP code execution (PMASA-2018-4)",
    },
    CveRecord {
        cve_id: "CVE-2019-6340",
        product: "Drupal",
        // NVD: 8.5.0..<8.5.11 AND 8.6.0..<8.6.10 (SA-CORE-2019-003).
        affected: VersionRange::Branches(&[("8.5.0", "8.5.11"), ("8.6.0", "8.6.10")]),
        cvss: 8.1,
        epss: 0.9192,
        kev: true,
        severity: Severity::High,
        summary: "Unsafe deserialization in REST/JSON:API enables unauth RCE (SA-CORE-2019-003)",
    },
];
